### ISSUE TITLE
add /home/vagrant (and /vagrant?) to $PATH

### ISSUE THREAD

**Issue by ecc11718** [indoorsdog/development-machine#10]
```
$ echo $PATH
$ /opt/rbenv/shims:/opt/rbenv/bin:/usr/local/bin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/vagrant_ruby/bin
```

`/home/vagrant` for sure.

**Comment by lukewpatterson** [comment]
executable files in /home ?

**Comment by ecc11718** [comment]
In `/home/vagrant` yea. For edge cases when there's no apt package nor npm/gem/etc, nor a *nix installer, but has an executable (e.g. [jslint](http://www.javascriptlint.com/download.htm)). 

(_There are other ways of obtaining jslint (from [npm](https://npmjs.org/package/nodelint)) but I'm sure there'll be edge cases where the above is true, in which case Chef's gotta put 'em somewhere_.)

**Comment by ecc11718** [comment]
Well, I guess the provisioning is all done `sudo` anyway. Forgot about that. Still it might be a way to _test_ that executable actually works/is what you want, before committing it to a recipe & re-provisioning.

**Comment by ecc11718** [comment]
I don't think this enhancement is necessary for the time being and am closing it until if/when needed.
