### ISSUE TITLE
python, make as Vagrantfile-config-friendly as fnichol's rbenv cookbook allows

### ISSUE THREAD

**Issue by lukewpatterson** [indoorsdog/development-machine#15]
this is going to be an ordeal

ok, so look here https://github.com/indoorsdog/development-machine/blob/a0a83b986bfa6c4a9bd976c7863b5377de55139c/Vagrantfile#L124

you see that `json` config in the `Vagrantfile` is very nice, one can easily tell which `rubies` are installed, and which `gems` installed in those `rubies`

so copy that pattern for `python` config, copying-like-crazy code patterns seen in @fnichol's [rbenv cookbok](https://github.com/fnichol/chef-rbenv/blob/4f96bb99edcc85584cfa9359e38c024684ef2634/recipes/user.rb).  nice touches like [introspection-boomerang-json config](https://github.com/fnichol/chef-rbenv/blob/4f96bb99edcc85584cfa9359e38c024684ef2634/recipes/user.rb#L50)

did I mention that is going to be an ordeal.  but it will be worth it

**Comment by lukewpatterson** [comment]
the recipe name should be `user_install`

**Comment by lukewpatterson** [comment]
something like this

```
  'virtualenv' => {
    'git_ref' => 'the current tag/release/stable',
    'user_installs' => [
      {
        'user' => 'vagrant',
        'pythons' => [ '2.7.3' ],
        'global' => '2.7.3',
        'packages' => {
          '2.7.3' => [
            {
              'name' => 'pygments',
              'version' => '1.5'
            }
          ]
        }
      }
    ]
  }
```

**Comment by lukewpatterson** [comment]
- [pythonbrew](https://github.com/utahta/pythonbrew) for installing `python`s
  - afaict, there is no `chef` `cookbook` for `pythonbrew`
- [virtualenv](www.virtualenv.org) for creating isolated load-path/environments within the `pythonbrew`-installed `python`s
  - there is a `chef` `cookbook` for this, but it doesn't tie it back through [pythonbrew's 'venv' command](https://github.com/utahta/pythonbrew/#usage), so I'm not sure how that part will work out 
- [pip](http://www.pip-installer.org/) for installing `package`s into the `virtualenv`-created environments
  - an example of a `python` package we will want is: [pygments](http://pygments.org/)

**Comment by lukewpatterson** [comment]
actually, some tweaks:

```
  'pythonbrew' => {
    'user_installs' => [
      {
        'user' => 'vagrant',
        'pythons' => [ '2.7.3' ],
        'defaults' => {
          'python' => '2.7.3',
          'venv' => 'default'
        },
        'venv' => {
          'default' => [
            {
              'name' => 'pygments',
              'version' => '1.5'
            }
          ]
        }
      }
    ]
  }
```

**Comment by ecc11718** [comment]
Not sure if you noticed or it's a user-error but `pygments` doesn't show up in the list of installed modules

``` bash
$ pydoc modules
```

I noticed that another module I added to the installation list in the pythonbrew node didn't install either.

**Comment by lukewpatterson** [comment]
argh, forgot to add 'defaults' to the bash startup scripts

other note, I think the `pip freeze` command might help more, when checking to see what is installed (yes, I know that command seems dumb, `freeze`?)   might as well be `explode` or `dither`

working on it now...

**Comment by ecc11718** [comment]
Cool. I couldn't get `pip freeze` to work (though there is an apt package for it and I bet a module). `pydoc modules` works fine, as does

``` python
>>> help('modules')
```

from the REPL and seemed to give a simple indication that `pygments` was missing.

**Comment by lukewpatterson** [comment]
i'm getting to close to fixing it.  appending `pythonbrew use` and `pythonbrew venv use` commands.  eta 15 minutes

**Comment by ecc11718** [comment]
FIrst `up`-ping a box, everything works. But `halt`ing and re-`up`-ping yields this error:

``` bash
[default] -- v-root: /vagrant
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p Using `Python-2.7.3`
# Using `default` environment (found in /home/vagrant/.pythonbrew/venvs/Python-2.7.3)
# To leave an environment, simply run `deactivate`
/vagrant
~/git/repo/development-machine$
```

Don't think it's a breaker/blocker. Just FYI.

**Comment by ecc11718** [comment]
Actually misspoke. Looks like a blocker on re-`provision`-ing.
