### ISSUE TITLE
ruby dev, rbenv and friends

### ISSUE THREAD

**Issue by lukewpatterson** [indoorsdog/development-machine#2]
[rbenv](https://github.com/sstephenson/ruby-build/)
[ruby-build](https://github.com/sstephenson/ruby-build/)

and add shell hooks

**Comment by lukewpatterson** [comment]
like, switch to https://github.com/fnichol/chef-rbenv as soon as possible

better docs, more 'watchers'.  ha!  # watchers as judge!

**Comment by lukewpatterson** [comment]
good enough start - https://github.com/indoorsdog/development-machine/blob/a0a83b986bfa6c4a9bd976c7863b5377de55139c/Vagrantfile#L124

ability to choose which rubies, and which gems for those rubies

**Comment by ecc11718** [comment]
I'm trying to grok why we're doing these "isolated runtimes." I see the benefit of doing this when you're developing on a box whose global environment you have/had no control over, when you need that separation for both sides of the coin. But here, the _whole_ point of this box is to develop on; I don't see a separate function, globally vs. locally. And with shell provisioning, we can ensure we get exactly what we want starting from the base box.

Why can't we feel safe with shell provisioning?

**Comment by lukewpatterson** [comment]
Before addressing your concerns, a general recap of my motivations for these type of configurations:  I'd like to select the specific versions of every lang needed for development, regardless of whether or not the lang is already installed in the base image of the os.

> @ecc11718: I see the benefit of doing this when you're developing on a box whose global environment you have/had no control over...

We really can't (or "shouldn't", based on conventional wisdom) update/change the system lang versions, regardless of whether the OS is running directly on real hardware or running in a vm.  If we don't install our own langs, we must accept whatever versions come preinstalled.

> @ecc11718: And with shell provisioning, we can ensure we get exactly what we want starting from the base box.

I see the choice of shell provisioning vs chef provisioning as independent (one even might say "orthogonal") of the decision to install version-specified langs.  Are they related more than I'm seeing?  Side note: In the Vagrant-land, I think the term 'base box' would be reserved to speak of the actual box that gets downloaded - in which case we really can't affect it via any provisioner.

**Comment by lukewpatterson** [comment]
I guess I can see how the downloaded box could still be called a 'base box', even after applying 'patches' related to selection/upgrade/installation of the provisioner that is intended for use the next phase.  I think it gets a little murkier when the 'patches' aren't solely for the sake of the upcoming provisioner's runtime needs.

**Comment by ecc11718** [comment]
> @lukewpatterson:  We really can't (or "shouldn't", based on conventional wisdom) update/change the system lang versions, regardless of whether the OS is running directly on real hardware or running in a vm. If we don't install our own langs/tools, we must accept whatever versions come preinstalled.

We can definitely update/change versions on the base box, since that's what `patches.sh` does. You're right that if we don't control that, we get what the base box has. Sounds like I need to understand why we _shouldn't_. I thought I understood, conventionally-speaking, the need was to not contaminate/rely upon global install space. But I'm arguing "global == local" here. I can't see how, say if we used strictly a shell provisioner, how _globally_ installing wouldn't achieve the same thing as installing _locally_.

Worst case scenario I _must_ be right if we do not rely upon base boxes but instead build one ourselves with the exact langs/tools and their versions.

> @ecc11718: And with shell provisioning, we can ensure we get exactly what we want **starting from** the base box.

I think the key phrase is "**starting from**." From my limited understanding of Vagrant (and `Vagrantfile` seems to confirm), we **start** from a base box and **from** there, provisioning a custom flavor. I could be wrong though.

It seems to me the better approach is to shell provision where _no other alternative to update/install can occur with recipes or other provisioner resources in `Vagrantfile`_ and to do so _globally_.

But I guess I should research the fear/worry/faux pas of relying on global resources (that I control the destiny of) on a box **strictly** built for developing.

**Comment by ecc11718** [comment]
A couple concerns I have if we go down the "private path:"
- We should re-evaluate what we've already done in `Vagrantfile`, determine what else needs _privatized_. Maybe you've already considered this.
- (_Considering my position is valid..._) Where "local version == global version" we are creating additional (unnecessary) provisioning time. A separate but related concern (goal), I believe is tacit now but should be stated for "Go Live" is, that we keep the building of these boxes _at minimum time_, only deviating from the base boxes where **we must**. We should target, all things being equal, the build-time under a few minutes. Again, when deviation must occur, we may be outside that target.

**Comment by ecc11718** [comment]
> @ecc11718: We can definitely update/change versions on the base box, since that's what `patches.sh` does. 

_Technically_ that could be construed as updating a base box without changing its `sha1` (ha) which is not true so I do mean this in the context I describe later on in the post, which is updating/changing **from** the base box.

Semantics.

**Comment by lukewpatterson** [comment]
We probably have to first answer this question: What will be developed on this _development-machine_ box?

After we answer that, then we can better decide the path forward.

Granted, development is such an individualized and customized process that we could never create anything that would be useable by everyone.  My quick back-of-napkin: the box is an opinionated environment for developing Node, Ruby and Python projects using modern ecosystem techniques and tools.

I'll have to think about the "lang installation, shell vs chef" and "broke your local" issues some more, can't articulate a view yet.

**Comment by ecc11718** [comment]
> @lukewpatterson: My quick back-of-napkin: the box is an opinionated environment for developing Node, Ruby and Python projects using modern ecosystem techniques and tools.

I've given this thought, too. Maybe we let [syntastic](https://github.com/scrooloose/syntastic/tree/master/syntax_checkers), at least in terms of compilation support, maybe not full tooling support, be a guide?

We should discuss this sometime, for sure. I am building for #3, as much compilation support as I can, at any rate.

**Comment by lukewpatterson** [comment]
or use this as our guide https://github.com/languages/
